export const UserMock = [
  {
    title: 'דיור',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'שכירות', amount: '' },
      { expense: 'קבוע', kind: 'ארנונה', amount: '' },
      { expense: 'משתנה', kind: 'מים', amount: '' },
      { expense: 'קבוע', kind: 'חשמל', amount: '' },
      { expense: 'קבוע', kind: 'גז', amount: '' },
      { expense: 'קבוע', kind: 'ועוד בית', amount: '' },
      { expense: 'קבוע', kind: 'ניקון וגינון', amount: '' },
      { expense: 'קבוע', kind: 'אחזקה ותיקונים', amount: '' },
      { expense: 'קבוע', kind: 'רכישות לבית', amount: '' },
      { expense: 'קבוע', kind: 'ביטוח דירה', amount: '' },
    ],
  },
  {
    title: 'תקשורת',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'טלויזיה', amount: '' },
      { expense: 'קבוע', kind: 'אינטרנט', amount: '' },
      { expense: 'משתנה', kind: 'סלולר', amount: '' },
    ],
  },
  {
    title: 'מזון וקניות',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'מזון', amount: '' },
      { expense: 'קבוע', kind: 'חומרי ניקוי וטואלטיקה', amount: '' },
      { expense: 'קבוע', kind: 'תרופות', amount: '' },
      { expense: 'קבוע', kind: 'בר מים', amount: '' },
      { expense: 'קבוע', kind: 'קפסולות קפה', amount: '' },
      { expense: 'קבוע', kind: 'סיגריות', amount: '' },
    ],
  },
  {
    title: 'טיפוח',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'קוסמטיקאית', amount: '' },
      { expense: 'קבוע', kind: 'איפור ובישום', amount: '' },
      { expense: 'קבוע', kind: 'מוצרי טיפוח', amount: '' },
    ],
  },
  {
    title: 'ביגוד',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'בגדים', amount: '' },
      { expense: 'קבוע', kind: 'נעליים', amount: '' },
      { expense: 'קבוע', kind: 'משקפיים', amount: '' },
    ],
  },
  {
    title: 'רכב ונסיעות',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'דלקליסינג', amount: '' },
      { expense: 'קבוע', kind: 'טיפולים ותיקונים', amount: '' },
      { expense: 'קבוע', kind: 'אגרת רכב,טסט', amount: '' },
      { expense: 'קבוע', kind: 'ביטוח רכב', amount: '' },
      { expense: 'קבוע', kind: 'תחבורה ציבורית', amount: '' },
      { expense: 'קבוע', kind: 'חניה', amount: '' },
      { expense: 'קבוע', kind: 'כבישי אגרה', amount: '' },
      { expense: 'קבוע', kind: 'שטיפת רכב', amount: '' },
    ],
  },
  {
    title: 'ילדים וחינוך',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'גנים', amount: '' },
      { expense: 'קבוע', kind: 'צהרון', amount: '' },
      { expense: 'קבוע', kind: 'בית ספר', amount: '' },
      { expense: 'קבוע', kind: 'ציוד לבי"ס', amount: '' },
      { expense: 'קבוע', kind: 'תחבורה והסעות', amount: '' },
      { expense: 'קבוע', kind: 'חוגיםתנועות נוערקייטנותבריכה', amount: '' },
      { expense: 'קבוע', kind: 'בייביסיטר', amount: '' },
      { expense: 'קבוע', kind: 'צעצועים ומשחקים', amount: '' },
      { expense: 'קבוע', kind: 'ימי הולדת', amount: '' },
      { expense: 'קבוע', kind: 'דמי כיס', amount: '' },
    ],
  },
  {
    title: 'פנאי ותחביבים',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'חופשות וטיולים,חו"ל', amount: '' },
      { expense: 'קבוע', kind: 'מסעדות', amount: '' },
      { expense: 'קבוע', kind: 'משלוחי אוכל', amount: '' },
      { expense: 'קבוע', kind: 'בילוי משפחתי', amount: '' },
      { expense: 'קבוע', kind: 'חדר כושר', amount: '' },
      { expense: 'קבוע', kind: 'מתנות ואירועים', amount: '' },
      { expense: 'קבוע', kind: 'לימודים', amount: '' },
      { expense: 'קבוע', kind: 'תחביבים', amount: '' },
      { expense: 'קבוע', kind: 'ייעוץ', amount: '' },
      { expense: 'קבוע', kind: 'אימון אישי', amount: '' },
    ],
  },
  {
    title: 'בריאות',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'קופ"ח,שב"ן,סיעודי', amount: '' },
      { expense: 'קבוע', kind: 'ביטוח בריאות פרטי,סיעודי פרטי', amount: '' },
      { expense: 'קבוע', kind: 'רופאים מקצועיים', amount: '' },
      { expense: 'קבוע', kind: 'ביטוח שינייםטיפולי שיניים', amount: '' },
      { expense: 'קבוע', kind: 'תרופות ותוספי תזונה', amount: '' },
      { expense: 'קבוע', kind: 'טיפולים משלימים', amount: '' },
      { expense: 'קבוע', kind: 'בריאות -אחר', amount: '' },
    ],
  },
  {
    title: 'ביטוחים ופיננסים',
    isLocked: true,
    rows: [
      { expense: 'קבוע', kind: 'ביטוח חיים א.כ.ע', amount: '' },
      { expense: 'קבוע', kind: 'יעוץ מקצועי', amount: '' },
      { expense: 'קבוע', kind: 'עלויות בנקאיות', amount: '' },
      { expense: 'קבוע', kind: 'עמלות כ.א', amount: '' },
    ],
  },
];
